function output = calculateChosenDistractor(dataStructure)
    
    % ------------------------ High PE ------------------------
    
    % Get the number of trials where the subject chose the distractor face
    nChoseDistractor_HighPE = length(returnIndicesIntersect(... % <N,T,D>
                                        dataStructure.PE,'high',...
                                        dataStructure.trialType,'3AFC',...
                                        dataStructure.button_pressed, 2,...
                                        dataStructure.faceType1, 'non-target',...
                                        dataStructure.faceType2, 'target',...
                                        dataStructure.faceType3, 'distractor'))...
                               +...
                               length(returnIndicesIntersect(... % <N,D,T>
                                        dataStructure.PE,'high',...
                                        dataStructure.trialType,'3AFC',...
                                        dataStructure.button_pressed, 1,...
                                        dataStructure.faceType1, 'non-target',...
                                        dataStructure.faceType2, 'distractor',...
                                        dataStructure.faceType3, 'target'))...
                               +...
                               length(returnIndicesIntersect(... % <D,N,T>
                                        dataStructure.PE,'high',...
                                        dataStructure.trialType,'3AFC',...
                                        dataStructure.button_pressed, 0,...
                                        dataStructure.faceType1, 'distractor',...
                                        dataStructure.faceType2, 'non-target',...
                                        dataStructure.faceType3, 'target'));
    
    % Get the percent of trials where the subject chose the distractor face
    percentChoseDistractor_HighPE = nChoseDistractor_HighPE/...
                                        length(returnIndicesIntersect(...
                                        dataStructure.PE,'high',...
                                        dataStructure.trialType,'3AFC'));
    
    % ------------------------ Low PE ------------------------
    
    % Get the number of trials where the subject chose the distractor face
    nChoseDistractor_LowPE = length(returnIndicesIntersect(... % <N,T,D>
                                        dataStructure.PE,'low',...
                                        dataStructure.trialType,'3AFC',...
                                        dataStructure.button_pressed, 2,...
                                        dataStructure.faceType1, 'non-target',...
                                        dataStructure.faceType2, 'target',...
                                        dataStructure.faceType3, 'distractor'))...
                               +...
                               length(returnIndicesIntersect(... % <N,D,T>
                                        dataStructure.PE,'low',...
                                        dataStructure.trialType,'3AFC',...
                                        dataStructure.button_pressed, 1,...
                                        dataStructure.faceType1, 'non-target',...
                                        dataStructure.faceType2, 'distractor',...
                                        dataStructure.faceType3, 'target'))...
                               +...
                               length(returnIndicesIntersect(... % <D,N,T>
                                        dataStructure.PE,'low',...
                                        dataStructure.trialType,'3AFC',...
                                        dataStructure.button_pressed, 0,...
                                        dataStructure.faceType1, 'distractor',...
                                        dataStructure.faceType2, 'non-target',...
                                        dataStructure.faceType3, 'target'));
    
    % Get the percent of trials where the subject chose the distractor face
    percentChoseDistractor_LowPE = nChoseDistractor_LowPE/...
                                        length(returnIndicesIntersect(...
                                        dataStructure.PE,'low',...
                                        dataStructure.trialType,'3AFC'));
                                    
    % --------- Return ---------
    output = [nChoseDistractor_HighPE, percentChoseDistractor_HighPE, nChoseDistractor_LowPE, percentChoseDistractor_LowPE];
    
    
end % End of function